spring.application.name=kfc

spring.datasource.url=jdbc:mysql://localhost:3306/kfcDatabase
spring.datasource.username=root
spring.datasource.password=v209@itvedant
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.date-format=dd/MM/yyyy
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testmail091011@gmail.com
spring.mail.password=qhthcfbfndzpnmxd



spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


RAZORPAY_KEY_ID=rzp_test_SMuM7WWUskn0rC
RAZORPAY_KEY_SECRET=hmHHHJhDALU1IJ6D4xGX3SvB